CREATE DATABASE chainsql DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
CREATE DATABASE monitor DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE DATABASE postgres DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
